-- ============================================================================
-- Migration: 0000_initial.sql
-- Description: Core schema definition for the Vigil observability system.
--              Sets up tables for users, projects, sessions, event summaries,
--              issue groups, issue instances, and AI triage logs.
-- ============================================================================

-- 1. Table: users
-- Represents the developer dashboard users authenticated with the Vigil platform.
CREATE TABLE users (
  id          TEXT PRIMARY KEY,       -- Unique user identifier (typically clerk/auth ID)
  email       TEXT NOT NULL UNIQUE,   -- Primary email address used for notifications and logging in
  name        TEXT,                   -- Display name of the user
  github_id   TEXT UNIQUE,            -- Connected GitHub identity identifier
  created_at  BIGINT NOT NULL         -- Epoch timestamp of account registration
);

-- 2. Table: projects
-- Telemetry targets/applications registered in Vigil. Each project is identified
-- by a public key credentials token during ingestion.
CREATE TABLE projects (
  id                               TEXT PRIMARY KEY,                  -- Unique internal project ID
  name                             TEXT NOT NULL,                     -- human-readable project title
  public_key                       TEXT NOT NULL UNIQUE,              -- Public API credentials used by the client-side SDK
  owner_id                         TEXT NOT NULL,                     -- Foreign key reference pointing to users.id
  github_repo                      TEXT,                              -- Linked GitHub repository namespace (e.g. owner/repo)
  github_token                     TEXT,                              -- Encrypted credentials token to raise issues on GitHub
  created_at                       BIGINT NOT NULL,                   -- Epoch timestamp of project registration

  -- GitHub automation policies:
  github_auto_raise_enabled        BOOLEAN NOT NULL DEFAULT false,    -- Toggles auto-raising GitHub issues from triaged P0s
  github_auto_raise_severity       TEXT    NOT NULL DEFAULT 'P0',     -- Minimum severity required to trigger auto-raise
  github_auto_raise_min_confidence REAL    NOT NULL DEFAULT 0.90,     -- Minimum AI confidence score needed to trigger issue creation
  github_comment_enabled           BOOLEAN NOT NULL DEFAULT false     -- Toggles updating existing issues with comment summaries
);

-- 3. Table: sessions
-- Captures metadata and aggregated telemetry outcomes for individual client session recordings.
CREATE TABLE sessions (
  id                    TEXT PRIMARY KEY,                   -- Unique session token generated by the SDK
  project_id            TEXT NOT NULL,                      -- Owner project foreign key

  -- Client Environment:
  url                   TEXT NOT NULL,                      -- Starting page URL address
  user_agent            TEXT,                               -- Raw browser agent string
  screen_width          INTEGER,                            -- Client browser width in pixels
  screen_height         INTEGER,                            -- Client browser height in pixels

  -- Release Tracking:
  release               TEXT,                               -- Custom release/build version tags
  commit_sha            TEXT,                               -- Source repository git commit identifier
  environment           TEXT,                               -- Deployment environment (e.g. production, preview)
  user_id_hash          TEXT,                               -- SHA-256 hashed end-user identifier for privacy preservation
  sdk_version           TEXT,                               -- Version of the client SDK sending the logs

  -- Telemetry State:
  duration_ms           INTEGER,                            -- Monotonically calculated elapsed session duration
  started_at            BIGINT NOT NULL,                    -- Session start timestamp (epoch ms)
  ended_at              BIGINT,                             -- Session end/finalization timestamp (epoch ms)
  created_at            BIGINT NOT NULL,                    -- Database row insertion timestamp

  -- Storage details:
  blob_path             TEXT,                               -- Disk filepath pointer to the gzipped raw rrweb replay events

  -- Native Telemetry Aggregates (Layer 1 metrics):
  has_js_error          BOOLEAN NOT NULL DEFAULT false,     -- Flags if session encountered any uncaught exceptions
  has_rage_click        BOOLEAN NOT NULL DEFAULT false,     -- Flags if session suffered user interaction friction
  has_network_err       BOOLEAN NOT NULL DEFAULT false,     -- Flags if session suffered API HTTP/fetch failures
  has_dead_click        BOOLEAN NOT NULL DEFAULT false,     -- Flags if session contains un-responsive user clicks
  error_count           INTEGER NOT NULL DEFAULT 0,         -- Total tally of client errors encountered

  -- AI Triage Aggregates (Layer 2 metrics):
  issue_instance_count  INTEGER NOT NULL DEFAULT 0,         -- Total unique issue instances raised during triage runs
  issue_group_count     INTEGER NOT NULL DEFAULT 0,         -- Total unique issue groups impacted in this session

  -- AI Triage Outcomes:
  ai_analyzed_at        BIGINT,                             -- Timestamp when AI triage finished analysis
  ai_analysis_skipped   BOOLEAN NOT NULL DEFAULT false,     -- Flags if session skipped triage (e.g., zero friction)
  ai_skip_reason        TEXT,                               -- Logged explanation for skipping AI triage
  ai_session_summary    TEXT,                               -- Human-readable summarized narrative generated by the LLM
  ai_goal_completed     BOOLEAN,                            -- Evaluated client goal success status
  ai_friction_score     INTEGER,                            -- Computed user frustration score (0 to 100 scale)
  ai_triage_confidence  REAL                                -- AI triage categorization confidence index score
);

-- 4. Table: events_summary
-- Holds parsed telemetry event instances for sessions. Each row is a key event
-- such as a rage click, JS error, console error, or navigation action.
CREATE TABLE events_summary (
  id              TEXT PRIMARY KEY,                         -- Unique event identifier
  session_id      TEXT NOT NULL,                            -- Parent session key
  project_id      TEXT NOT NULL,                            -- Parent project key

  type            TEXT NOT NULL,                            -- Event type classification enum
  timestamp_ms    BIGINT NOT NULL,                          -- Timestamp of event occurrence
  target          TEXT,                                     -- Target UI element selector or click target data

  -- Typed context payload fields:
  error_message   TEXT,                                     -- Exception message if type is error
  error_stack     TEXT,                                     -- Callstack trace block if type is error
  network_url     TEXT,                                     -- Endpoint URL if type is network error
  network_status  INTEGER,                                  -- HTTP response status code
  network_method  TEXT,                                     -- HTTP request method (e.g. POST, GET)
  click_count     INTEGER,                                  -- Aggregated click counts for rage/dead clicks
  nav_to          TEXT,                                     -- Navigation destination path

  fingerprint     TEXT,                                     -- Deterministic SHA-256 fingerprint generated from event criteria
  created_at      BIGINT NOT NULL                           -- Row creation timestamp
);

-- 5. Table: issue_groups
-- Represents deduplicated groups of issues consolidated by their unique fingerprint signature.
CREATE TABLE issue_groups (
  id                               TEXT PRIMARY KEY,                  -- Unique issue group ID
  project_id                       TEXT NOT NULL,                     -- Project owner target reference

  fingerprint                      TEXT NOT NULL,                     -- Unique SHA-256 fingerprint signature
  title                            TEXT NOT NULL,                     -- Normalized title describing the root exception/fault
  root_cause                       TEXT,                              -- AI evaluated structural cause breakdown
  suggested_fix                    TEXT,                              -- AI generated markdown recommendation to resolve the issue
  severity                         TEXT NOT NULL,                     -- Computed severity index level (P0, P1, P2)
  status                           TEXT NOT NULL DEFAULT 'open',      -- Resolution lifecycle state ('open', 'resolved', etc.)
  confidence                       REAL,                              -- System confidence scoring for this categorization

  reproduction_steps_json          TEXT,                              -- JSON array of steps leading to the error state
  evidence_summary                 TEXT,                              -- Summary of the system states at the time of failure

  affected_session_count           INTEGER NOT NULL DEFAULT 0,        -- Total count of distinct sessions impacted by this issue group
  first_seen_at                    BIGINT NOT NULL,                   -- Timestamp when the issue fingerprint was first logged
  last_seen_at                     BIGINT NOT NULL,                   -- Timestamp when the issue was last reported

  -- Integration links:
  github_issue_url                 TEXT,                              -- Linked GitHub issues URL
  github_issue_number              INTEGER,                           -- Linked GitHub issue ID sequence number
  github_auto_raised               BOOLEAN NOT NULL DEFAULT false,    -- Flags if this issue group was auto-created on GitHub
  github_last_comment_at           BIGINT,                            -- Tracker for last sync update comments
  github_last_comment_session_count INTEGER,                           -- Session count checkpoint at last comment

  created_at                       BIGINT NOT NULL,                   -- Group creation timestamp
  updated_at                       BIGINT NOT NULL                    -- Group modification timestamp
);

-- 6. Table: issue_instances
-- Captures individual occurrences of issues within sessions, attaching them to their respective groups.
CREATE TABLE issue_instances (
  id                    TEXT PRIMARY KEY,                   -- Unique instance token
  issue_group_id        TEXT NOT NULL,                      -- Target issue group foreign key
  session_id            TEXT NOT NULL,                      -- Impacted session foreign key
  project_id            TEXT NOT NULL,                      -- Owner project foreign key

  title                 TEXT NOT NULL,                      -- Localized instance error title
  root_cause            TEXT,                               -- Localized instance root cause evaluation
  suggested_fix         TEXT,                               -- Localized instance suggested solution path
  severity              TEXT NOT NULL,                      -- Computed instance severity
  timestamp_ms          BIGINT,                             -- Event timestamp
  confidence            REAL,                               -- Local confidence rating

  evidence_json         TEXT,                               -- Session trace variables at occurrence
  reproduction_json     TEXT,                               -- Sequence of events leading to this issue

  dev_comment           TEXT,                               -- Developer feedback/notes on this instance

  created_at            BIGINT NOT NULL                     -- Database row creation timestamp
);

-- 7. Table: ai_triage_runs
-- Diagnostic logger table to record LLM invocations and monitor operational tokens/error rates.
CREATE TABLE ai_triage_runs (
  id                    TEXT PRIMARY KEY,                   -- Unique run identifier
  session_id            TEXT NOT NULL,                      -- Analyzed target session reference
  project_id            TEXT NOT NULL,                      -- Analyzed target project reference

  model                 TEXT NOT NULL,                      -- Specific LLM model version string used (e.g. gemini-2.5-pro)
  prompt_version        TEXT NOT NULL,                      -- Tag identifier for prompt format versioning
  status                TEXT NOT NULL,                      -- Triage job outcome ('completed', 'failed', etc.)
  input_tokens          INTEGER,                            -- Count of prompt tokens consumed
  output_tokens         INTEGER,                            -- Count of generation tokens consumed
  error_message         TEXT,                               -- Captured API or logic exception strings if failed

  created_at            BIGINT NOT NULL,                    -- Start time of triage execution
  completed_at          BIGINT                              -- Resolution time of triage execution
);

-- Indexes: Performance & Telemetry Lookup optimization
-- Optimizes: loading recent sessions for a project (e.g., live dashboard feeds).
CREATE INDEX idx_sessions_project_started
  ON sessions (project_id, started_at DESC);

-- Optimizes: listing friction-heavy user sessions prioritizing worst user experiences.
CREATE INDEX idx_sessions_project_friction
  ON sessions (project_id, ai_friction_score DESC);

-- Optimizes: querying sequential interaction lists for a replay session.
CREATE INDEX idx_events_summary_session_time
  ON events_summary (session_id, timestamp_ms);

-- Optimizes: looking up unresolved issue groups under active investigation.
CREATE INDEX idx_issue_groups_project_status
  ON issue_groups (project_id, status, last_seen_at DESC);

-- Optimizes: sorting issue groups based on impact volume and priority levels.
CREATE INDEX idx_issue_groups_project_severity
  ON issue_groups (project_id, severity, affected_session_count DESC);

-- Optimizes: querying all occurrences of a specific issue group during drills.
CREATE INDEX idx_issue_instances_group
  ON issue_instances (issue_group_id, created_at DESC);

-- Optimizes: fetching all issues associated with a single user recording.
CREATE INDEX idx_issue_instances_session
  ON issue_instances (session_id);
