/**
 * @file ingest-schema.ts
 * @description Zod validation schemas for ingestion request payloads.
 * @how Declares schemas with strict bounds on fields, batch event counts (max 500), and summary events (max 50).
 * @why Enforces structural contract validation at the edge before any database/disk processing begins.
 */

import { z } from "zod";

/**
 * SummaryEventSchema
 * Validates summarized client telemetry events generated by the SDK.
 * Includes explicit character caps on error message strings and stacks to prevent memory allocation abuse.
 */
const SummaryEventSchema = z.object({
  type: z.enum([
    "js_error",
    "rage_click",
    "dead_click",
    "network_error",
    "navigation",
    "console_error",
    "click",
    "significant_click"
  ]),
  timestampMs: z.number().int().positive(),
  target: z.unknown().optional(),
  
  // JS/Console error details
  errorMessage: z.string().max(5000).optional(), // Caps raw error messages to 5KB
  errorStack: z.string().max(10000).optional(),  // Caps raw error stacks to 10KB
  message: z.string().max(5000).optional(),
  stack: z.string().max(10000).optional(),
  source: z.string().max(2048).optional(),
  line: z.number().int().nonnegative().optional(),
  column: z.number().int().nonnegative().optional(),
  handled: z.boolean().optional(),
  timestamp: z.number().int().positive().optional(),
  argumentSummaries: z.array(z.string().max(2000)).optional(),

  // Network request details
  networkUrl: z.string().max(2048).optional(),
  networkStatus: z.number().int().optional(),
  networkMethod: z.string().max(20).optional(),

  // Rage click metrics
  clickCount: z.number().int().optional(),
  area: z.object({
    minX: z.number(),
    maxX: z.number(),
    minY: z.number(),
    maxY: z.number()
  }).optional(),

  // Dead click click-coordinates and timers
  x: z.number().optional(),
  y: z.number().optional(),
  waitTimeMs: z.number().optional(),

  // Navigation URLs and state-change actions
  navFrom: z.string().max(2048).optional(),
  navTo: z.string().max(2048).optional(),
  navigationType: z.enum(["pushState", "replaceState", "popstate", "hashchange"]).optional(),
}).strict();

/**
 * SessionMetadataSchema
 * Validates the metadata header payload block describing the client environment.
 */
const SessionMetadataSchema = z.object({
  url: z.string().max(2048), // Root page URL
  userAgent: z.string().max(1000), // Client device agent string
  startedAt: z.number().int().positive(), // Timestamp when session started
  screenWidth: z.number().int().positive(),
  screenHeight: z.number().int().positive(),
  environment: z.enum(["development", "preview", "production"]).optional(),
  release: z.string().max(255).optional(), // Application release version
  commitSha: z.string().max(255).optional(), // Commit hash of deployment
  userId: z.string().max(255).optional(), // Authenticated user ID string
}).strict();

/**
 * IngestPayloadSchema
 * Root schema enforcing payload constraints on every incoming ingestion request.
 * Enforces strict limits: max 50 summary events and max 500 raw interaction events.
 */
export const IngestPayloadSchema = z.object({
  projectKey: z.string().min(1).max(255), // Credentials public key matching project
  sessionId: z.string().refine((val) => {
    const isUuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(val);
    if (isUuid) return true;
    if (process.env.NODE_ENV !== "production") {
      return val.length <= 100 && /^sess_[a-zA-Z0-9_-]+$/i.test(val);
    }
    return false;
  }, {
    message: "Invalid sessionId format. Must be a valid UUID, or non-production sess_ prefix format (max 100 chars).",
  }),
  metadata: SessionMetadataSchema,
  summary: z.array(SummaryEventSchema).max(50), // Caps aggregated event summaries to 50 items per payload
  events: z.array(z.unknown()).max(500), // Caps raw replay events to 500 items per payload
  isFinal: z.boolean(), // Flag indicating if session has ended (triggers finalization)
  sdkVersion: z.string().max(50)
}).strict();

export type IngestPayload = z.infer<typeof IngestPayloadSchema>;
export type SummaryEvent = z.infer<typeof SummaryEventSchema>;
