import type { Project, IssueGroup, Session, IssueInstance, EventSummary } from "./types";

const NOW = Date.now();
const ago = (h: number) => NOW - h * 3600_000;

// ─── PROJECT ────────────────────────────────────────────────────────────────
export const MOCK_PROJECT: Project = {
  id: "proj_a1b2c3",
  name: "Checkout App",
  public_key: "pk_live_vg_c8f2a91d3e4b5f6a",
  github_repo: "acme/checkout-app",
  github_auto_raise_enabled: true,
  github_auto_raise_severity: "P0+P1",
  github_auto_raise_min_confidence: 0.9,
  github_comment_enabled: true,
};

// ─── SESSIONS ───────────────────────────────────────────────────────────────
export const MOCK_SESSIONS: Session[] = [
  {
    id: "ses_x9y8z7", project_id: "proj_a1b2c3",
    url: "/checkout", user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/124.0 Safari/537.36",
    screen_width: 1920, screen_height: 1080,
    release: "web-2026.05.08", commit_sha: "a81f9d", environment: "production",
    duration_ms: 142000, started_at: ago(2), ended_at: ago(2) + 142000,
    has_js_error: true, has_rage_click: false, has_network_err: true, has_dead_click: false,
    error_count: 2, issue_instance_count: 2, issue_group_count: 1,
    ai_analyzed_at: ago(1.5), ai_analysis_skipped: false,
    ai_session_summary: "User navigated directly to /checkout, bypassing the cart page. Payment handler crashed immediately on undefined cart.items access. User attempted to reload twice before abandoning.",
    ai_goal_completed: false, ai_friction_score: 92, ai_triage_confidence: 0.97,
  },
  {
    id: "ses_m3n4p5", project_id: "proj_a1b2c3",
    url: "/dashboard", user_agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_4) AppleWebKit/537.36 Chrome/123.0 Safari/537.36",
    screen_width: 2560, screen_height: 1600,
    release: "web-2026.05.07", commit_sha: "b93e12", environment: "production",
    duration_ms: 88000, started_at: ago(4), ended_at: ago(4) + 88000,
    has_js_error: false, has_rage_click: false, has_network_err: true, has_dead_click: false,
    error_count: 0, issue_instance_count: 1, issue_group_count: 1,
    ai_analyzed_at: ago(3.5), ai_analysis_skipped: false,
    ai_session_summary: "User returned to the app after an extended absence. Auth token had silently expired, resulting in a redirect loop between /dashboard and /login. User eventually closed the tab.",
    ai_goal_completed: false, ai_friction_score: 85, ai_triage_confidence: 0.91,
  },
  {
    id: "ses_q7r8s9", project_id: "proj_a1b2c3",
    url: "/checkout", user_agent: "Mozilla/5.0 (iPhone; CPU iPhone OS 17_4 like Mac OS X) AppleWebKit/605.1.15 Mobile/15E148 Safari/604.1",
    screen_width: 390, screen_height: 844,
    release: "web-2026.05.08", commit_sha: "a81f9d", environment: "production",
    duration_ms: 234000, started_at: ago(5), ended_at: ago(5) + 234000,
    has_js_error: false, has_rage_click: true, has_network_err: false, has_dead_click: true,
    error_count: 0, issue_instance_count: 2, issue_group_count: 2,
    ai_analyzed_at: ago(4.5), ai_analysis_skipped: false,
    ai_session_summary: "Mobile user attempted to apply a promo code. After the first failed attempt, the submit button became non-functional. User rage-clicked the button 6 times, then clicked a dead 'Continue' button before abandoning.",
    ai_goal_completed: false, ai_friction_score: 78, ai_triage_confidence: 0.88,
  },
  {
    id: "ses_t1u2v3", project_id: "proj_a1b2c3",
    url: "/checkout/address", user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Firefox/125.0",
    screen_width: 1440, screen_height: 900,
    release: "web-2026.05.06", commit_sha: "c74d55", environment: "production",
    duration_ms: 195000, started_at: ago(7), ended_at: ago(7) + 195000,
    has_js_error: false, has_rage_click: false, has_network_err: true, has_dead_click: false,
    error_count: 0, issue_instance_count: 1, issue_group_count: 1,
    ai_analyzed_at: ago(6.5), ai_analysis_skipped: false,
    ai_session_summary: "User entered an unusual UK postcode format. The form passed client-side validation but the shipping API rejected it with 422. The confirmation page rendered blank with no error. User waited 30 seconds before leaving.",
    ai_goal_completed: false, ai_friction_score: 65, ai_triage_confidence: 0.84,
  },
  {
    id: "ses_w4x5y6", project_id: "proj_a1b2c3",
    url: "/products", user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/124.0 Safari/537.36",
    screen_width: 1920, screen_height: 1080,
    release: "web-2026.05.08", commit_sha: "a81f9d", environment: "production",
    duration_ms: 320000, started_at: ago(10), ended_at: ago(10) + 320000,
    has_js_error: false, has_rage_click: false, has_network_err: false, has_dead_click: false,
    error_count: 0, issue_instance_count: 0, issue_group_count: 0,
    ai_analyzed_at: ago(9.5), ai_analysis_skipped: false,
    ai_session_summary: "User browsed the product catalogue, added two items to cart, and proceeded through checkout successfully. Smooth session with no friction points detected.",
    ai_goal_completed: true, ai_friction_score: 12, ai_triage_confidence: 0.95,
  },
  {
    id: "ses_a1b2c3", project_id: "proj_a1b2c3",
    url: "/products/shoes", user_agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 13_6) AppleWebKit/537.36 Chrome/122.0 Safari/537.36",
    screen_width: 1280, screen_height: 800,
    release: "web-2026.05.07", commit_sha: "b93e12", environment: "production",
    duration_ms: 180000, started_at: ago(12), ended_at: ago(12) + 180000,
    has_js_error: false, has_rage_click: false, has_network_err: false, has_dead_click: false,
    error_count: 0, issue_instance_count: 0, issue_group_count: 0,
    ai_analyzed_at: ago(11.5), ai_analysis_skipped: false,
    ai_session_summary: "User browsed the shoes category, filtered by size, and added a pair to the wishlist. Did not proceed to checkout in this session.",
    ai_goal_completed: true, ai_friction_score: 8, ai_triage_confidence: 0.92,
  },
  {
    id: "ses_d4e5f6", project_id: "proj_a1b2c3",
    url: "/checkout", user_agent: "Mozilla/5.0 (Linux; Android 14; Pixel 8) AppleWebKit/537.36 Chrome/124.0 Mobile Safari/537.36",
    screen_width: 412, screen_height: 915,
    release: "web-2026.05.08", commit_sha: "a81f9d", environment: "production",
    duration_ms: 67000, started_at: ago(14), ended_at: ago(14) + 67000,
    has_js_error: true, has_rage_click: false, has_network_err: true, has_dead_click: false,
    error_count: 1, issue_instance_count: 1, issue_group_count: 1,
    ai_analyzed_at: ago(13.5), ai_analysis_skipped: false,
    ai_session_summary: "Mobile user hit the payment 503 during peak hours. The page showed no feedback. User waited briefly and abandoned.",
    ai_goal_completed: false, ai_friction_score: 70, ai_triage_confidence: 0.93,
  },
  {
    id: "ses_g7h8i9", project_id: "proj_a1b2c3",
    url: "/home", user_agent: "Mozilla/5.0 (iPad; CPU OS 17_4 like Mac OS X) AppleWebKit/605.1.15 Mobile/15E148 Safari/604.1",
    screen_width: 1024, screen_height: 1366,
    release: "web-2026.05.06", commit_sha: "c74d55", environment: "production",
    duration_ms: 450000, started_at: ago(20), ended_at: ago(20) + 450000,
    has_js_error: false, has_rage_click: false, has_network_err: false, has_dead_click: false,
    error_count: 0, issue_instance_count: 0, issue_group_count: 0,
    ai_analyzed_at: ago(19.5), ai_analysis_skipped: false,
    ai_session_summary: "Long tablet session. User browsed home page, navigated to multiple product categories, and read product reviews. Did not convert but showed high engagement.",
    ai_goal_completed: false, ai_friction_score: 18, ai_triage_confidence: 0.89,
  },
  {
    id: "ses_j1k2l3", project_id: "proj_a1b2c3",
    url: "/checkout", user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/124.0 Safari/537.36",
    screen_width: 1366, screen_height: 768,
    release: "web-2026.05.08", commit_sha: "a81f9d", environment: "production",
    duration_ms: 95000, started_at: ago(22), ended_at: ago(22) + 95000,
    has_js_error: true, has_rage_click: false, has_network_err: true, has_dead_click: false,
    error_count: 2, issue_instance_count: 2, issue_group_count: 1,
    ai_analyzed_at: ago(21.5), ai_analysis_skipped: false,
    ai_session_summary: "Another direct /checkout navigation. Same TypeError as igr_001. User refreshed once and got a different error before closing.",
    ai_goal_completed: false, ai_friction_score: 90, ai_triage_confidence: 0.96,
  },
  {
    id: "ses_m4n5o6", project_id: "proj_a1b2c3",
    url: "/account/orders", user_agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_4) Safari/605.1.15",
    screen_width: 1440, screen_height: 900,
    release: "web-2026.05.07", commit_sha: "b93e12", environment: "production",
    duration_ms: 280000, started_at: ago(30), ended_at: ago(30) + 280000,
    has_js_error: false, has_rage_click: false, has_network_err: false, has_dead_click: false,
    error_count: 0, issue_instance_count: 0, issue_group_count: 0,
    ai_analyzed_at: ago(29.5), ai_analysis_skipped: false,
    ai_session_summary: "User reviewed their order history, clicked on a past order for details, and updated their shipping address. Smooth session.",
    ai_goal_completed: true, ai_friction_score: 5, ai_triage_confidence: 0.98,
  },
  {
    id: "ses_p7q8r9", project_id: "proj_a1b2c3",
    url: "/checkout", user_agent: "Mozilla/5.0 (Windows NT 11.0; Win64; x64) Chrome/124.0",
    screen_width: 1920, screen_height: 1080,
    release: "web-2026.05.08", commit_sha: "a81f9d", environment: "preview",
    duration_ms: 55000, started_at: ago(36), ended_at: ago(36) + 55000,
    has_js_error: false, has_rage_click: false, has_network_err: true, has_dead_click: false,
    error_count: 0, issue_instance_count: 1, issue_group_count: 1,
    ai_analyzed_at: ago(35.5), ai_analysis_skipped: false,
    ai_session_summary: "Preview environment session. Payment API returned 503. User saw no error message and abandoned after 55 seconds.",
    ai_goal_completed: false, ai_friction_score: 55, ai_triage_confidence: 0.87,
  },
  {
    id: "ses_s1t2u3", project_id: "proj_a1b2c3",
    url: "/products/electronics", user_agent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Chrome/123.0 Safari/537.36",
    screen_width: 1920, screen_height: 1200,
    release: "web-2026.05.06", commit_sha: "c74d55", environment: "production",
    duration_ms: 520000, started_at: ago(48), ended_at: ago(48) + 520000,
    has_js_error: false, has_rage_click: false, has_network_err: false, has_dead_click: false,
    error_count: 0, issue_instance_count: 0, issue_group_count: 0,
    ai_analyzed_at: ago(47.5), ai_analysis_skipped: false,
    ai_session_summary: "Long research session on the electronics category. User compared multiple laptops, read reviews, and saved to wishlist. Did not purchase in this session.",
    ai_goal_completed: false, ai_friction_score: 15, ai_triage_confidence: 0.91,
  },
];

// ─── EVENTS (for session ses_x9y8z7) ────────────────────────────────────────
export const MOCK_EVENTS: EventSummary[] = [
  { id: "evt_001", session_id: "ses_x9y8z7", type: "navigation", timestamp_ms: 0, target: null, error_message: null, error_stack: null, network_url: null, network_status: null, network_method: null, click_count: null, nav_to: "/checkout", fingerprint: null },
  { id: "evt_002", session_id: "ses_x9y8z7", type: "click", timestamp_ms: 4200, target: "#pay-btn", error_message: null, error_stack: null, network_url: null, network_status: null, network_method: null, click_count: 1, nav_to: null, fingerprint: null },
  { id: "evt_003", session_id: "ses_x9y8z7", type: "network_error", timestamp_ms: 4350, target: null, error_message: null, error_stack: null, network_url: "/api/cart", network_status: 200, network_method: "GET", click_count: null, nav_to: null, fingerprint: null },
  { id: "evt_004", session_id: "ses_x9y8z7", type: "js_error", timestamp_ms: 4380, target: null, error_message: "TypeError: Cannot read properties of undefined (reading 'id')", error_stack: "TypeError: Cannot read properties of undefined (reading 'id')\n    at paymentHandler (paymentHandler.ts:47:23)\n    at handleSubmit (CheckoutForm.tsx:112:5)\n    at HTMLButtonElement.onclick (checkout/page.tsx:89:12)", network_url: null, network_status: null, network_method: null, click_count: null, nav_to: null, fingerprint: "fp_payment_typeerror" },
  { id: "evt_005", session_id: "ses_x9y8z7", type: "network_error", timestamp_ms: 12400, target: null, error_message: null, error_stack: null, network_url: "/api/payment", network_status: 500, network_method: "POST", click_count: null, nav_to: null, fingerprint: "fp_payment_network" },
  { id: "evt_006", session_id: "ses_x9y8z7", type: "navigation", timestamp_ms: 45000, target: null, error_message: null, error_stack: null, network_url: null, network_status: null, network_method: null, click_count: null, nav_to: "/checkout", fingerprint: null },
  { id: "evt_007", session_id: "ses_x9y8z7", type: "js_error", timestamp_ms: 48000, target: null, error_message: "ReferenceError: cart is not defined", error_stack: "ReferenceError: cart is not defined\n    at initPayment (paymentHandler.ts:22:8)\n    at CheckoutPage.useEffect (checkout/page.tsx:44:3)", network_url: null, network_status: null, network_method: null, click_count: null, nav_to: null, fingerprint: "fp_payment_typeerror" },
];

// ─── ISSUE INSTANCES ────────────────────────────────────────────────────────
export const MOCK_ISSUE_INSTANCES: IssueInstance[] = [
  {
    id: "ins_001", issue_group_id: "igr_001", session_id: "ses_x9y8z7",
    title: "TypeError: Cannot read properties of undefined (reading 'id')",
    root_cause: "cart.items is undefined — user navigated directly to /checkout",
    suggested_fix: "Add null check on cart.items before accessing index",
    severity: "P0", timestamp_ms: 4380, confidence: 0.97,
    evidence_json: JSON.stringify([{ type: "js_error", message: "TypeError: Cannot read properties of undefined (reading 'id')", file: "paymentHandler.ts", line: 47 }]),
    reproduction_json: JSON.stringify(["Navigate directly to /checkout", "Click Pay"]),
    dev_comment: null,
  },
  {
    id: "ins_002", issue_group_id: "igr_005", session_id: "ses_x9y8z7",
    title: "POST /api/payment → 500",
    root_cause: "Payment service returned 500 after JS error recovery attempt",
    suggested_fix: "Add retry with back-off for payment API calls",
    severity: "P1", timestamp_ms: 12400, confidence: 0.91,
    evidence_json: JSON.stringify([{ type: "network_error", url: "/api/payment", status: 500, method: "POST" }]),
    reproduction_json: JSON.stringify(["Proceed to payment", "Observe 500 response"]),
    dev_comment: null,
  },
];

// ─── ISSUE GROUPS ───────────────────────────────────────────────────────────
export const MOCK_ISSUES: IssueGroup[] = [
  {
    id: "igr_001",
    project_id: "proj_a1b2c3",
    fingerprint: "fp_payment_typeerror",
    title: "TypeError: Cannot read properties of undefined (reading 'id') in payment handler",
    root_cause: "The `cart.items` array is undefined when the user navigates directly to /checkout without going through the cart page, causing the payment handler to crash when it tries to access `cart.items[0].id`.",
    suggested_fix: "Add a null check before accessing `cart.items`. If undefined, redirect to /cart with an error message. Consider initialising cart state from session storage on mount.",
    severity: "P0",
    status: "open",
    confidence: 0.97,
    reproduction_steps_json: JSON.stringify([
      "Open the app in a new tab",
      "Navigate directly to /checkout (skip cart page)",
      "Click 'Proceed to Payment'",
      "Observe TypeError thrown in console — payment form freezes"
    ]),
    evidence_summary: "Crash occurs in 34 sessions. All share a direct /checkout navigation without a prior /cart visit. Stack trace consistently points to paymentHandler.ts:47.",
    affected_session_count: 34,
    first_seen_at: ago(72),
    last_seen_at: ago(1),
    github_issue_url: null,
    github_issue_number: null,
    github_auto_raised: false,
  },
  {
    id: "igr_002",
    project_id: "proj_a1b2c3",
    fingerprint: "fp_auth_silent_logout",
    title: "Silent session expiry causes auth loop on /dashboard without user notification",
    root_cause: "The JWT refresh token silently expires after 24h. The API returns 401 but the client catches the error and redirects to /login without clearing local state, causing an infinite redirect loop.",
    suggested_fix: "Intercept 401 responses globally. Clear auth state, show a toast 'Your session has expired', then redirect to /login. Implement token refresh before expiry using a 5-minute pre-expiry window.",
    severity: "P1",
    status: "open",
    confidence: 0.91,
    reproduction_steps_json: JSON.stringify([
      "Log in and leave the tab open for 24+ hours",
      "Return and try to navigate to /dashboard",
      "Observe redirect loop between /dashboard and /login",
      "No error message shown to user"
    ]),
    evidence_summary: "Affects 18 sessions. Pattern: session starts >24h after last login. Network log shows repeated 401s on GET /api/me.",
    affected_session_count: 18,
    first_seen_at: ago(120),
    last_seen_at: ago(3),
    github_issue_url: "https://github.com/acme/checkout-app/issues/147",
    github_issue_number: 147,
    github_auto_raised: true,
  },
  {
    id: "igr_003",
    project_id: "proj_a1b2c3",
    fingerprint: "fp_address_validation",
    title: "Address form accepts invalid postcodes and fails silently at order confirmation",
    root_cause: "Client-side postcode validation regex does not cover all UK postcode formats. Invalid values pass the form but are rejected by the shipping API, which returns a 422. The error is swallowed and the user sees a blank confirmation page.",
    suggested_fix: "Use a comprehensive UK postcode validation library. Display inline field errors on 422 responses from the shipping API. Add an error boundary to the confirmation page.",
    severity: "P2",
    status: "open",
    confidence: 0.84,
    reproduction_steps_json: JSON.stringify([
      "Add items to cart and proceed to checkout",
      "Enter a valid-looking but incorrect postcode (e.g. 'SW1A 9ZZ')",
      "Click 'Continue to confirmation'",
      "Observe blank page — no error shown"
    ]),
    evidence_summary: "12 sessions. All entered non-standard postcode formats. Shipping API returns 422 on each.",
    affected_session_count: 12,
    first_seen_at: ago(48),
    last_seen_at: ago(6),
    github_issue_url: "https://github.com/acme/checkout-app/issues/152",
    github_issue_number: 152,
    github_auto_raised: false,
  },
  {
    id: "igr_004",
    project_id: "proj_a1b2c3",
    fingerprint: "fp_promo_rage",
    title: "Promo code field unresponsive after first failed attempt — triggers rage clicks",
    root_cause: "After a failed promo code submission, the input is disabled but the disabled state is not visually indicated. Users repeatedly click the non-functional button.",
    suggested_fix: "Show a clear disabled state on the promo input after failure. Re-enable after 3 seconds with a countdown label. Add inline error text below the field.",
    severity: "P1",
    status: "open",
    confidence: 0.88,
    reproduction_steps_json: JSON.stringify([
      "Add item to cart",
      "Enter an invalid promo code and submit",
      "Observe the button becomes unresponsive with no visual feedback",
      "Click the button 4+ times (rage click)"
    ]),
    evidence_summary: "9 sessions. Median rage click count: 6. All sessions abandon within 30s of the rage click event.",
    affected_session_count: 9,
    first_seen_at: ago(36),
    last_seen_at: ago(5),
    github_issue_url: null,
    github_issue_number: null,
    github_auto_raised: false,
  },
  {
    id: "igr_005",
    project_id: "proj_a1b2c3",
    fingerprint: "fp_payment_network",
    title: "POST /api/payment intermittently returns 503 during peak hours",
    root_cause: "The payment microservice is rate-limited at the infrastructure level. Under high load, requests queue and time out, returning 503 to the client with no retry logic in place.",
    suggested_fix: "Implement exponential back-off retry (max 3 attempts) for payment API calls. Show a 'Processing...' state to users during retries. Alert on-call if 503 rate exceeds 1% per 5 minutes.",
    severity: "P1",
    status: "linked",
    confidence: 0.93,
    reproduction_steps_json: JSON.stringify([
      "Simulate peak load (concurrent users)",
      "Attempt payment at checkout",
      "Observe intermittent 503 from /api/payment",
      "Page shows no feedback — user is stuck"
    ]),
    evidence_summary: "22 sessions in a 2h peak window. All hit 503 on POST /api/payment. Sessions cluster between 18:00–20:00 UTC.",
    affected_session_count: 22,
    first_seen_at: ago(168),
    last_seen_at: ago(2),
    github_issue_url: "https://github.com/acme/checkout-app/issues/139",
    github_issue_number: 139,
    github_auto_raised: false,
  },
  {
    id: "igr_006",
    project_id: "proj_a1b2c3",
    fingerprint: "fp_mobile_nav",
    title: "Mobile navigation menu does not close after route change",
    root_cause: "The mobile hamburger menu state is not reset on router navigation events. After clicking a nav link, the overlay remains open.",
    suggested_fix: "Subscribe to Next.js router events and close the menu on `routeChangeStart`. Add a close button to the menu overlay as a fallback.",
    severity: "P2",
    status: "open",
    confidence: 0.79,
    reproduction_steps_json: JSON.stringify([
      "Open app on mobile viewport",
      "Open hamburger menu",
      "Click any nav link",
      "Observe menu stays open on the new page"
    ]),
    evidence_summary: "7 sessions. All on screen_width < 768. Menu overlay persists after navigation in all cases.",
    affected_session_count: 7,
    first_seen_at: ago(24),
    last_seen_at: ago(8),
    github_issue_url: null,
    github_issue_number: null,
    github_auto_raised: false,
  },
  {
    id: "igr_007",
    project_id: "proj_a1b2c3",
    fingerprint: "fp_console_warn",
    title: "React key prop missing in product list map — console warnings in development",
    root_cause: "The product list renders without unique key props, causing React reconciliation warnings. No user-facing impact but pollutes developer console.",
    suggested_fix: "Add `key={product.id}` to each mapped product element.",
    severity: "P3",
    status: "ignored",
    confidence: 0.72,
    reproduction_steps_json: JSON.stringify([
      "Open app in development mode",
      "Navigate to /products",
      "Open browser console",
      "Observe React key prop warning"
    ]),
    evidence_summary: "Dev-only. No user impact. 3 sessions flagged in development environment.",
    affected_session_count: 3,
    first_seen_at: ago(200),
    last_seen_at: ago(48),
    github_issue_url: null,
    github_issue_number: null,
    github_auto_raised: false,
  },
  {
    id: "igr_008",
    project_id: "proj_a1b2c3",
    fingerprint: "fp_img_lcp",
    title: "Hero image on /home loads without priority hint — LCP degraded on slow connections",
    root_cause: "The hero `<img>` tag lacks `fetchpriority='high'` and is not preloaded. On 3G, LCP exceeds 4s.",
    suggested_fix: "Use Next.js `<Image priority>` on the hero. Add a `<link rel='preload'>` in the document head. Serve WebP with a JPEG fallback.",
    severity: "P3",
    status: "open",
    confidence: 0.68,
    reproduction_steps_json: JSON.stringify([
      "Open app on simulated 3G throttling",
      "Navigate to /home",
      "Observe delayed hero image load",
      "Check Lighthouse LCP score"
    ]),
    evidence_summary: "Performance issue, no crash. Detected via network_error events on slow connections.",
    affected_session_count: 5,
    first_seen_at: ago(96),
    last_seen_at: ago(12),
    github_issue_url: null,
    github_issue_number: null,
    github_auto_raised: false,
  },
];
